### ISSUE TITLE
iframeのレスポンシブ対応

### ISSUE THREAD

**Issue by sakelog** [sakelog/nextjs_blog#183]
Markdown内のiframeをレスポンシブ対応する。
中のsrcがYouTubeか判断して、Youtubeなら比率16:9で固定

**Comment by sakelog** [comment]
## 修正

スタイルシートを適用してレスポンシブ表示に対応した。

`src/lib/remark/remarkIframe.tsx`

```tsx
import styles from '../../styles/Object/Component/_c-article__iframe.module.scss';

const RemarkIframe: React.FC<JSX.IntrinsicElements['iframe']> = (props) => {
  const YOUTUBE_URL_NOCOOKIE = 'https://www.youtube-nocookie.com/embed/';
  const isYoutube = props.src.startsWith(YOUTUBE_URL_NOCOOKIE);

  const className = isYoutube ? 'youtube' : 'default';

  console.log(isYoutube);
  return (
    <div className={styles[className]}>
      <iframe {...props} />
    </div>
  );
};

export default RemarkIframe;

```

`src/styles/Object/Component/_c-article__iframe.module.scss`

```scss
@use '../../Foundation/variables' as *;

.default {
  position: relative;
  width: 100%;
  max-width: $sm;
  overflow: hidden;
  margin: 2rem;
  &::before {
    content: '';
    display: block;
    width: 100%;
    position: relative;
    padding-top: 100%;
  }
  iframe {
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
  }
}
.youtube {
  @extend .default;
  &::before {
    padding-top: (9/16) * 100%;
  }
}
```

URLで判断してYouTubeだったら16:9表示、それ以外のiframeは1:1表示にしている。

今はYoutubeの埋め込みコードのURLのみ判断しているので、今後URLの対象は追加を検討する。
