### ISSUE TITLE
カエレバデザイン修正

### ISSUE THREAD

**Issue by sakelog** [sakelog/nextjs_blog#184]
カエレバのデザインが一部崩れているので修正する。
商品画像が画面幅に応じて変わるようにする。

**Comment by sakelog** [comment]
## 修正

`src/styles/Object/Component/_c-article__yomereba.scss`

```scss
@use '../../Foundation/variables' as *;
@use '../../Foundation/mixin' as *;

$gray: #333333;
$white: #ffffff;

$amazon: #e89713;
$rakuten: #d91414;
/* ************************************* */
/* カエレバ、ヨメレバ、トマレバ */
/* ************************************* */
.kaerebalink-box,
.booklink-box,
.tomarebalink-box {
  ・
  ・ //省略
  ・ 
  .kaerebalink-image,
  .booklink-image {
    width: 100%;
    max-width: $xs;
    margin: auto;
    text-align: center;
    img {
      width: 100%;
      height: auto;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
    }
  }
  ・
  ・ //省略
  ・
}

```

`  .kaerebalink-image` , `.booklink-image`に`width` , `height`の記載がなかったので追加
